DELETE http://localhost:8090/api/clientes/get/1
Accept: application/json

###

PUT http://localhost:8090/api/clientes/get/1
Content-Type: application/json

{
  "nombres": "Carlos Ernesto",
  "documento": 1082749257,
  "celular": "3163930876"
}

###

GET http://localhost:8090/api/clientes/get/1
Accept: application/json

###
POST http://localhost:8090/api/clientes/all
Content-Type: application/json

{
  "nombres": "Carlos Ernesto",
  "documento": 1082749257
}

###
GET http://localhost:8090/api/clientes/all
Accept: application/json

###
