DELETE http://localhost:8090/api/productos/get/3
Accept: application/json

###

PUT http://localhost:8090/api/productos/get/2
Content-Type: application/json

{
  "nombre": "Salchipapa Mixta",
  "precioCompra": 6000.0,
  "precioVenta": 7000.0
}

###

GET http://localhost:8090/api/productos/get/2
Accept: application/json

###
POST http://localhost:8090/api/productos/all
Content-Type: application/json

{
  "nombre": "Salchipapa BBQ",
  "precioCompra": 5000.0,
  "precioVenta": 6000.0
}

###
GET http://localhost:8090/api/productos/all
Accept: application/json

###
